import { IMG } from "./images";
import type { EventPageData } from "@/components/EventPageTemplate";

const baseIncluded = [
    { title: "Two RAMP-certified bartenders", description: "Professional, friendly, and trained in responsible service." },
    { title: "Full bar setup & breakdown", description: "We arrive 90 minutes early and leave your space spotless." },
    { title: "All glassware & barware", description: "Crystal coupes, highballs, cocktail picks, shakers — the works." },
    { title: "Fresh garnishes & mixers", description: "Citrus pressed the morning of, blossoms picked the night before." },
    { title: "Premium ice & coolers", description: "Crystal-clear cubes plus iced wells for whites and bubbles." },
    { title: "Liability & liquor insurance", description: "Full coverage for your venue and guests, every event." },
];

const baseRelated = [
    { slug: "weddings", label: "Weddings", image: IMG.eventWeddings },
    { slug: "bridal-showers", label: "Bridal Showers", image: IMG.eventBridalShower },
    { slug: "baby-showers", label: "Baby Showers", image: IMG.eventBabyShower },
    { slug: "corporate", label: "Corporate", image: IMG.eventCorporate },
    { slug: "birthdays", label: "Birthdays", image: IMG.eventBirthdays },
    { slug: "wellness", label: "Wellness", image: IMG.eventWellness },
    { slug: "engagement", label: "Engagements", image: IMG.eventEngagement },
    { slug: "backyard", label: "Backyard", image: IMG.eventBackyard },
];

function related(currentSlug: string, take = 4) {
    return baseRelated.filter((e) => e.slug !== currentSlug).slice(0, take);
}

export const EVENTS: Record<string, EventPageData> = {
    weddings: {
        slug: "weddings",
        eyebrow: "Weddings",
        title: "Wedding bartending that blooms",
        description: "Custom cocktail menus, the Bloom Bar set against your florals, and labels with your couple's name on every coupe.",
        heroImage: IMG.eventWeddings,
        intro: {
            eyebrow: "For Your Big Day",
            heading: "Your wedding deserves more than a standard cocktail hour",
            body: "We design a bar experience that fits inside your venue's florals like it was always meant to be there. From your signature cocktail to the very last toast, every detail is intentional — and yes, every glass gets your initials.",
        },
        included: baseIncluded,
        signatureTouches: [
            { title: "Two custom signature cocktails", description: "One for each of you — designed in a tasting call. The 'Bride's' tends to be pink-petal-pretty. The 'Groom's' tends to be smoke-show smart." },
            { title: "Custom-printed cup labels", description: "Your couple's name, your wedding hashtag, your date — printed on every cup. Guests photograph these. A lot." },
            { title: "Champagne tower option", description: "Add a tiered champagne tower for your reception entrance — built tableside, poured on cue." },
            { title: "Coordination with your planner", description: "We sync with your planner or coordinator from week-of through the event so the timeline flows." },
            { title: "After-party transition", description: "Reception bar by 6pm. Espresso martinis by 10pm. Late-night espresso bar by midnight if you want it." },
        ],
        pricing: {
            startingAt: "$850",
            package: "Most weddings book The Luxe",
            details: "5 hours of service · 2-3 bartenders · custom menu (3 signatures) · crystal glassware upgrade · day-of coordination · priority booking. We build a custom proposal once we know your guest count and venue.",
        },
        gallery: [IMG.eventWeddings, IMG.cocktailRose, IMG.bloomBar, IMG.customLabeled, IMG.champagneTower, IMG.weddingTable],
        testimonial: {
            quote: "The Blooming Tini didn't just bartend our wedding — they turned the bar into the most photographed corner of the night. Every guest asked for the signature cocktail recipe.",
            author: "Sarah & Michael",
            role: "Wedding · October 2024",
        },
        faqs: [
            { q: "How far in advance should we book?", a: "For 2026 weddings, we recommend booking 6-9 months out, especially May-October. We can sometimes accommodate shorter notice — just ask." },
            { q: "Can you create cocktails matching our wedding colors?", a: "Absolutely — color-matching is one of our favorite parts. Send us your palette and we'll propose drinks that photograph beautifully against your florals." },
            { q: "Do you handle alcohol purchasing?", a: "We operate dry-hire (you buy the bottles, we pour). We'll send you a shopping list with exact quantities calibrated to your guest count and event length." },
            { q: "What about a champagne tower or special moment?", a: "Add-ons like champagne towers, sparkler send-offs, and late-night espresso bars are all popular. Mention them in your inquiry and we'll include them in your proposal." },
        ],
        relatedEvents: related("weddings"),
    },
    "bridal-showers": {
        slug: "bridal-showers",
        eyebrow: "Bridal Showers",
        title: "Bridal showers worthy of the bride",
        description: "Pink champagne, custom-labeled cocktails, and the kind of styling she'll remember when she's toasting her future grandchildren.",
        heroImage: IMG.eventBridalShower,
        intro: {
            eyebrow: "Toasts To Her",
            heading: "She's saying yes to one person. The shower says yes to all her people.",
            body: "Bridal showers are our favorite love letter to friendship. We design pretty-pink menus, custom-labeled flutes, and a bar that becomes the photo wall by itself.",
        },
        included: baseIncluded,
        signatureTouches: [
            { title: "Pink cocktail flight", description: "Three signature drinks built around her wedding palette — typically rose, peach, and champagne notes." },
            { title: "Custom labels with her initials", description: "Every glass printed with her future last name (or her favorite hashtag)." },
            { title: "Mocktail station", description: "Pregnant bridesmaid? Sober sister? Our mocktails are just as styled as our cocktails." },
            { title: "Photo-ready bar styling", description: "Florals, vintage cake stands, ribbon bows — we style for Instagram from the first sip." },
            { title: "Bride's surprise cocktail", description: "We design a secret 'first sip' just for her, presented when she arrives." },
        ],
        pricing: {
            startingAt: "$550",
            package: "Most showers book The Premium",
            details: "4 hours of service · 2 bartenders · custom 3-cocktail menu · custom labels · mocktail station · day-of coordination. Perfect for 40-100 guests in homes, conservatories, or restaurants.",
        },
        gallery: [IMG.eventBridalShower, IMG.cocktailRose, IMG.customLabeled, IMG.matchaLatte, IMG.cocktailChampagneBloom, IMG.garnishDetail],
        testimonial: {
            quote: "From the first call to the final glass collected, every detail was handled. My bridal shower felt like we had stepped into a fairytale florist's dream.",
            author: "Ava & Family",
            role: "Bridal Shower · August 2024",
        },
        faqs: [
            { q: "Can you set up in a private home?", a: "Yes — we set up beautifully in homes, sunrooms, backyards, and rented venues. We bring the bar; we just need a small footprint." },
            { q: "Do you do brunch showers?", a: "Always. Our Blooming Brunch menu — Aperol Spritz, Bloody Mary, Tropical Mimosa, Peach Bellini — is built for daytime showers." },
            { q: "Can the bride approve the cocktails before the event?", a: "Many maids of honor send us the bride's drink preferences and we'll design around them — sometimes as a surprise, sometimes as a Zoom tasting." },
        ],
        relatedEvents: related("bridal-showers"),
    },
    "baby-showers": {
        slug: "baby-showers",
        eyebrow: "Baby Showers",
        title: "Baby showers, blooming",
        description: "Mocktails, custom-labeled lemonades, and gorgeous styling that fits perfectly between the diaper cake and the gender reveal balloons.",
        heroImage: IMG.eventBabyShower,
        intro: {
            eyebrow: "For The Mom-To-Be",
            heading: "Toast her without the bourbon",
            body: "We specialize in alcohol-free experiences that still feel celebratory. Custom mocktails, sparkling pink lemonades on iridescent cake stands, and labels with baby's name (if she's sharing it).",
        },
        included: baseIncluded.map((i, idx) => idx === 0 ? { ...i, title: "Mocktail-trained bartenders", description: "Our team specializes in mocktails that taste as good as they look." } : i),
        signatureTouches: [
            { title: "Custom-labeled mocktail line", description: "Sparkling lemonades, virgin Berry Blooms, and citrus spritzers — each labeled with baby's name or initials." },
            { title: "Iridescent serving display", description: "Pink iridescent cake stands at varied heights — peak Instagram styling." },
            { title: "Mom-safe ingredient sheet", description: "Every ingredient labeled, allergen-checked, and verified pregnancy-safe — we send the full ingredient list with your proposal." },
            { title: "Optional alcohol-bar for guests", description: "Want a small alcohol selection for non-pregnant guests? We can do both bars side by side." },
            { title: "Take-home favor cocktail kits", description: "Send guests home with a cute mocktail kit to recreate the day." },
        ],
        pricing: {
            startingAt: "$450",
            package: "Most baby showers book Mocktail Premium",
            details: "3 hours of service · 1-2 mocktail-trained bartenders · custom 3-mocktail menu · custom labels · sparkling display setup. Tailored for 30-80 guests in homes, restaurants, or private venues.",
        },
        gallery: [IMG.eventBabyShower, IMG.matchaLatte, IMG.cocktailCitrus, IMG.customLabeled, IMG.garnishDetail, IMG.glassware],
        testimonial: {
            quote: "Everyone said it was the prettiest baby shower they've ever been to. The custom-labeled mocktails were every guest's favorite detail.",
            author: "Maya P.",
            role: "Baby Shower · January 2025",
        },
        faqs: [
            { q: "Is everything truly alcohol-free?", a: "Yes — for a pure baby shower setup, we use only mocktail ingredients with no alcohol whatsoever. We can also do a split bar with alcohol on one side, mocktails on the other." },
            { q: "Can the mocktails match a gender reveal theme?", a: "Pink-blue color palettes are some of our favorite to design. We've done sapphire blueberry sips next to blush strawberry spritzes." },
            { q: "Do you work with bakers/florists?", a: "Yes — we love coordinating styling with the rest of your vendor team. We'll share our setup plan in advance so everything blooms together." },
        ],
        relatedEvents: related("baby-showers"),
    },
    corporate: {
        slug: "corporate",
        eyebrow: "Corporate Events",
        title: "Corporate, with character",
        description: "Premium bar service for launches, holiday parties, retreats, and client appreciation events — refined enough for your boardroom, fun enough for after-hours.",
        heroImage: IMG.eventCorporate,
        intro: {
            eyebrow: "For Your Brand",
            heading: "When the dress code is business but the vibe is celebration",
            body: "We bring full liability insurance, RAMP certification, and the polish to elevate any corporate occasion — from holiday parties to product launches to team retreats. Branded labels available.",
        },
        included: baseIncluded,
        signatureTouches: [
            { title: "Brand-labeled cocktails", description: "Print your company logo, product name, or launch tagline on every cup." },
            { title: "Premium glassware tier", description: "Crystal coupes and tumblers for events where the photography matters." },
            { title: "Discreet, professional service", description: "Bartenders trained in corporate hospitality — refined service, no rowdy energy." },
            { title: "Quote-ready invoicing", description: "Net-30 invoicing, COI on file, W-9 ready — all the procurement boxes ticked." },
            { title: "Repeat-event discounts", description: "Holiday party, quarterly socials, summer retreat? We offer multi-event pricing for repeat clients." },
        ],
        pricing: {
            startingAt: "$650",
            package: "Most corporate clients book The Premium",
            details: "4 hours of service · 2 bartenders · custom 2-cocktail menu (often a signature + a classic) · branded labels · COI provided. Most corporate events 50-150 guests.",
        },
        gallery: [IMG.eventCorporate, IMG.glassware, IMG.cocktailMartini, IMG.heroBar, IMG.cocktailSmoke, IMG.bartenderAction],
        testimonial: {
            quote: "Punctual, polished, and unbelievably kind. They handled a 200-person launch with the calm of a 5-star hotel. We've already re-booked them for our holiday party.",
            author: "Jennifer R.",
            role: "VP Marketing · December 2024",
        },
        faqs: [
            { q: "Can you provide a Certificate of Insurance?", a: "Yes — we carry $2M general liability + liquor liability and can name your company or venue as additional insured. Standard turnaround is 48 hours from request." },
            { q: "Do you accept Net-30 invoicing?", a: "Yes for corporate clients. We can also accept ACH, credit card, or checks. Talk to us about your AP requirements during the proposal stage." },
            { q: "Can our team brand-label the cocktails?", a: "Always. Send us your logo/lockup and we'll proof labels for your approval before printing." },
        ],
        relatedEvents: related("corporate"),
    },
    birthdays: {
        slug: "birthdays",
        eyebrow: "Birthdays & Milestones",
        title: "A birthday bar worth a milestone",
        description: "Whether it's a sweet 16, a glittery 30th, or a champagne-tower 50th, we build a bar that becomes the celebration.",
        heroImage: IMG.eventBirthdays,
        intro: {
            eyebrow: "Make It A Moment",
            heading: "30, 40, 50 — the bar should be as big a deal as the cake",
            body: "We do milestone birthdays for a living. From signature cocktails matched to your party theme to balloon arches behind our bar setup, every detail is designed to make your guest of honor feel adored.",
        },
        included: baseIncluded,
        signatureTouches: [
            { title: "Signature 'guest of honor' cocktail", description: "Designed around their favorite spirit and named after them. Their initials on every cup." },
            { title: "Themed menu design", description: "Garden party, old Hollywood, disco, Bridgerton — we'll match your theme down to the garnish." },
            { title: "Espresso martini bar", description: "The 10pm crowd favorite — we set up a dedicated espresso martini station for late-night energy." },
            { title: "Cake-cutting timing", description: "We coordinate with you so the champagne flutes are passed exactly when the cake comes out." },
            { title: "Party photographer-ready styling", description: "Our bar setup is designed to be the backdrop of every Instagram story from the night." },
        ],
        pricing: {
            startingAt: "$550",
            package: "Most birthdays book The Premium",
            details: "4 hours of service · 2 bartenders · custom 3-cocktail menu · themed styling · custom labels. Great for 40-120 guests in homes, restaurants, or venues.",
        },
        gallery: [IMG.eventBirthdays, IMG.cocktailEspresso, IMG.cocktailBerry, IMG.customLabeled, IMG.heroChampagne, IMG.cocktailMartini],
        testimonial: {
            quote: "I told them my theme was 'garden party meets old Hollywood' — they brought edible flowers, custom menus, and a champagne tower. My 40th felt like a magazine spread.",
            author: "Lauren M.",
            role: "Milestone Birthday · September 2024",
        },
        faqs: [
            { q: "Can you match a specific theme?", a: "We love themed events. Send us a Pinterest board or a few inspiration images and we'll build cocktails, labels, and styling to match." },
            { q: "Do you do sweet 16 / non-alcohol birthdays?", a: "Yes — we have full mocktail packages for under-21 milestones that look just as styled as our cocktail menus." },
            { q: "What if my home is small?", a: "Our bar setup fits in a corner with a 6×3 foot footprint. We've poured in dining rooms, garages, and backyards." },
        ],
        relatedEvents: related("birthdays"),
    },
    wellness: {
        slug: "wellness",
        eyebrow: "Wellness & Pilates",
        title: "Matcha bars for the soft-life crowd",
        description: "Custom-labeled matcha lattes, sparkling adaptogens, and the prettiest mocktails on the wellness scene — built for Pilates socials, retreats, and launches.",
        heroImage: IMG.eventWellness,
        intro: {
            eyebrow: "The Matcha Bar",
            heading: "Where wellness meets photographable",
            body: "We saw a gap in the wellness event scene — beautiful drinks without alcohol. Our matcha bar specializes in ceremonial-grade matcha lattes, adaptogen tonics, and custom-labeled mocktails for Pilates studios, retreats, brand launches, and wellness-aligned weddings.",
        },
        included: [
            { title: "Ceremonial-grade matcha", description: "Whisked by hand, the way it should be — never powdered shortcuts." },
            { title: "Custom-labeled cups", description: "Your studio name, your retreat brand, your event hashtag." },
            { title: "Pink iridescent serving display", description: "Vintage cake stands of varying heights for the perfect photo moment." },
            { title: "Adaptogen & superfood options", description: "Ashwagandha, lion's mane, reishi — for the truly wellness-aligned crowd." },
            { title: "Oat, almond, & coconut milks", description: "Multiple plant-based milk options at every event, no exceptions." },
            { title: "Mocktail station available", description: "Sparkling cucumber tonics, hibiscus refreshers — for the post-Pilates social hour." },
        ],
        signatureTouches: [
            { title: "Strawberry Soft Life Matcha", description: "Our most-requested wellness drink — ceremonial matcha, fresh strawberry, oat milk, edible flower garnish." },
            { title: "Lavender Vanilla Matcha", description: "House-made lavender syrup, vanilla bean, ceremonial matcha — calming and pretty." },
            { title: "Custom retreat branding", description: "Your retreat name on every cup, your color palette in every drink." },
        ],
        pricing: {
            startingAt: "$450",
            package: "Wellness events typically book the Matcha Bar package",
            details: "3 hours of service · 1-2 baristas · custom 3-drink matcha menu · custom labels · iridescent display setup · oat/almond/coconut milks. Sized for 30-100 guests at studios, retreats, or brand events.",
        },
        gallery: [IMG.eventWellness, IMG.matchaLatte, IMG.cocktailEspresso, IMG.customLabeled, IMG.garnishDetail, IMG.cocktailCitrus],
        testimonial: {
            quote: "As we prepared for our client's Soft Life Social, our strawberry matcha got the most honest review possible… toddler-approved. We'll take it.",
            author: "The Blooming Tini",
            role: "Strawberry Matcha · Soft Life Social",
        },
        faqs: [
            { q: "Do you offer alcohol-free events only?", a: "We can do pure mocktail/matcha events OR split-bar with alcohol available — whatever fits your wellness brand." },
            { q: "Can you accommodate dietary restrictions?", a: "Yes — we work with vegan, gluten-free, dairy-free, low-sugar, and most major restrictions. Mention them in your inquiry." },
            { q: "Do you partner with Pilates studios?", a: "We work with studios across Philadelphia and South Jersey. We offer discounted rates for recurring monthly socials." },
        ],
        relatedEvents: related("wellness"),
    },
    engagement: {
        slug: "engagement",
        eyebrow: "Engagement Parties",
        title: "She said yes. Now let's pour.",
        description: "Intimate engagement celebrations with custom toasts, signature 'first cocktail as a couple,' and a bar that doubles as the photo backdrop.",
        heroImage: IMG.eventEngagement,
        intro: {
            eyebrow: "Their First Toast As An 'Us'",
            heading: "The engagement party is the rehearsal for the wedding bar",
            body: "Engagement parties are often where we meet our wedding clients. We design a small but beautiful bar moment that previews what's coming on the big day — and gets your wedding party excited.",
        },
        included: baseIncluded,
        signatureTouches: [
            { title: "'First Cocktail As Us' design", description: "We design the couple's signature drink — they get to taste it for the first time at the party." },
            { title: "Custom 'She Said Yes' labels", description: "Glasses labeled with their initials, their proposal date, or just 'She Said Yes'." },
            { title: "Engagement ring photo styling", description: "We coordinate with your photographer to style the ring shot with our bar." },
            { title: "Champagne toast moment", description: "A passed champagne tray for the official engagement toast, on cue." },
            { title: "Sneak peek of wedding menu", description: "If we're booking your wedding, we use the engagement party as the cocktail tasting." },
        ],
        pricing: {
            startingAt: "$450",
            package: "Most engagements book The Essential or Premium",
            details: "3-4 hours of service · 1-2 bartenders · custom 2-cocktail menu · custom labels · day-of coordination. Tailored for 30-100 guests in homes, restaurants, or backyards.",
        },
        gallery: [IMG.eventEngagement, IMG.cocktailChampagneBloom, IMG.cocktailRose, IMG.customLabeled, IMG.heroChampagne, IMG.garnishDetail],
        testimonial: {
            quote: "We loved them so much at our engagement party that we booked them for the wedding before the night was over.",
            author: "Olivia & James",
            role: "Engagement Party · July 2024",
        },
        faqs: [
            { q: "If we use you for our engagement, do we get a discount on our wedding?", a: "Yes — we offer 10% off your wedding package when you book us for the engagement first. Just mention it during your wedding inquiry." },
            { q: "Can you do a small intimate gathering?", a: "Absolutely — we do engagements as small as 20 guests, in homes, restaurants, or backyards." },
            { q: "Can we surprise our partner with a signature cocktail?", a: "Surprise cocktails are some of our favorite moments. We'll work secretly with whichever partner is planning." },
        ],
        relatedEvents: related("engagement"),
    },
    backyard: {
        slug: "backyard",
        eyebrow: "Backyard Parties",
        title: "Backyard parties, elevated",
        description: "From neighborhood block parties to backyard birthday brunches, we bring the bar that turns a cookout into a celebration.",
        heroImage: IMG.eventBackyard,
        intro: {
            eyebrow: "Where The Best Parties Live",
            heading: "Your backyard. Our bar. Their best summer night.",
            body: "Backyard events are where we really shine — string lights, vintage rugs, fresh florals from the garden. We bring the Bloom Bar and you bring the people. Within an hour, the cookout becomes the talk of the cul-de-sac.",
        },
        included: baseIncluded,
        signatureTouches: [
            { title: "Outdoor-ready setup", description: "Weatherproof tabletops, shade umbrellas, and ice that lasts in summer heat." },
            { title: "Garden-to-glass garnishes", description: "If you have a herb garden, we'll use it. Mint, basil, rosemary, edible flowers — straight from your yard." },
            { title: "Frozen cocktail option", description: "Frozen rosé slushies and frozen espresso martinis are summer-event MVPs." },
            { title: "Family-friendly mocktail station", description: "Same styling, no alcohol — for the under-21 crowd and the designated drivers." },
            { title: "Backup plan for rain", description: "We bring a pop-up canopy and rain tarp to every outdoor event, just in case." },
        ],
        pricing: {
            startingAt: "$450",
            package: "Most backyard parties book The Essential",
            details: "3 hours of service · 1-2 bartenders · custom 2-cocktail menu · outdoor-ready setup. Great for 25-75 guests in backyards, decks, and outdoor spaces.",
        },
        gallery: [IMG.eventBackyard, IMG.outdoorBar, IMG.cocktailBerry, IMG.cocktailCitrus, IMG.heroFloralArch, IMG.garnishDetail],
        testimonial: {
            quote: "Our annual block party leveled up. The neighbors are still talking about the rosé slushies six months later.",
            author: "The Williams Family",
            role: "Backyard Block Party · July 2024",
        },
        faqs: [
            { q: "What if it rains?", a: "We bring a pop-up canopy for outdoor events. If forecast is severe, we'll discuss moving the bar inside (garage, sunroom, etc.) the day before." },
            { q: "Do we need a permit?", a: "For private backyard events on residential property, generally no. For block parties closing public streets, you may need a permit — we'll guide you." },
            { q: "Can you handle bigger neighborhood events?", a: "We've poured for 150+ at block parties with multiple bar stations. Send us guest count and we'll scope accordingly." },
        ],
        relatedEvents: related("backyard"),
    },
};
